/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ge.apm.ingestor.beans;

public class DataElement {
	private java.lang.Double v;

 	public void setV(java.lang.Double v) {
		this.v = v;
	}

	public java.lang.Double getV() {
		return v;
	}

	private java.lang.Long ts;

 	public void setTs(java.lang.Long  ts) {
		this.ts = ts;
	}

	public java.lang.Long  getTs() {
		return ts;
	}

	private java.lang.String q = "3";

 	public void setQ(java.lang.String q) {
		this.q = q;
	}

	public java.lang.String getQ() {
		return q;
	}

}