/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ge.apm.ingestor.beans;

import java.util.ArrayList;
import java.util.List;

public class Ingestor {
	private  List<TagElement> tags = new ArrayList<TagElement>();

 	public void setTags( List<TagElement> tags) {
		this.tags = tags;
	}

	public  List<TagElement> getTags() {
		return tags;
	}

}